# Generated by Django 6.0.5 on 2026-05-31 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('excerpt', models.TextField()),
                ('content', models.TextField()),
                ('author', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=60)),
                ('image_url', models.URLField(blank=True)),
                ('published_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('tagline', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon_name', models.CharField(max_length=50)),
                ('bg_class', models.CharField(default='bg-blue-50', max_length=60)),
                ('icon_class', models.CharField(default='text-blue-600', max_length=60)),
                ('founded', models.CharField(max_length=20)),
                ('fleet', models.CharField(max_length=50)),
                ('countries', models.CharField(max_length=20)),
                ('employees', models.CharField(max_length=20)),
                ('image_url', models.URLField(blank=True)),
                ('highlights', models.JSONField(default=list)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('company_name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('job_type', models.CharField(choices=[('Full-Time', 'Full-Time'), ('Sea-Based', 'Sea-Based'), ('Contract', 'Contract')], default='Full-Time', max_length=30)),
                ('department', models.CharField(max_length=80)),
                ('description', models.TextField()),
                ('posted_date', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-posted_date'],
            },
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('company', models.CharField(blank=True, max_length=100)),
                ('service_type', models.CharField(max_length=100)),
                ('origin', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('weight', models.CharField(blank=True, max_length=50)),
                ('dimensions', models.CharField(blank=True, max_length=100)),
                ('message', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='pending', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('icon_name', models.CharField(max_length=50)),
                ('features', models.JSONField(default=list)),
                ('image_url', models.URLField(blank=True, default='')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_number', models.CharField(max_length=30, unique=True)),
                ('status', models.CharField(choices=[('picked_up', 'Cargo Received'), ('in_transit', 'Vessel In Transit'), ('customs', 'At Customs / Port'), ('at_port', 'At Destination Port'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered')], default='picked_up', max_length=30)),
                ('origin', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('service_type', models.CharField(max_length=100)),
                ('weight', models.CharField(blank=True, max_length=30)),
                ('estimated_delivery', models.DateField(blank=True, null=True)),
                ('sender_name', models.CharField(blank=True, max_length=100)),
                ('receiver_name', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('bio', models.TextField()),
                ('image_url', models.URLField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('review', models.TextField()),
                ('rating', models.PositiveSmallIntegerField(default=5)),
                ('avatar_url', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrackingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('event_time', models.DateTimeField()),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='core.shipment')),
            ],
            options={
                'ordering': ['-event_time'],
            },
        ),
    ]
