# Generated by Django 6.0.5 on 2026-06-16 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_add_service_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutHighlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'About Highlight',
                'verbose_name_plural': 'About Highlights',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CareerPerk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('desc', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Career Perk',
                'verbose_name_plural': 'Career Perks',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Commitment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='FaqItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300)),
                ('answer', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'FAQ Item',
                'verbose_name_plural': 'FAQ Items',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Industry',
                'verbose_name_plural': 'Industries',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ShipmentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('desc', models.CharField(max_length=200)),
                ('icon', models.CharField(help_text='Icon name (e.g. box, truck, anchor)', max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Shipment Type',
                'verbose_name_plural': 'Shipment Types',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='Augustus Corp', max_length=100)),
                ('tagline', models.CharField(default='End-to-End Logistics Solutions — Reliable · Scalable · On-Time', max_length=200)),
                ('phone', models.CharField(default='803-666-8368', max_length=30)),
                ('email', models.EmailField(default='garry@augustusbrokerage.com', max_length=254)),
                ('address', models.CharField(default='United States & Canada', max_length=200)),
                ('website', models.CharField(default='augustustransport.com', max_length=100)),
                ('hours_weekday', models.CharField(default='8am–6pm ET', max_length=50)),
                ('hours_saturday', models.CharField(default='9am–2pm ET', max_length=50)),
                ('footer_blurb', models.TextField(default='Nationwide trucking & freight solutions across all 48 U.S. states and Canada. OTR, Drayage, Warehousing & Cross-Border — backed by a vetted carrier network.')),
                ('meta_description', models.TextField(default='Augustus Corp — End-to-end logistics solutions. Reliable, scalable, on-time freight across the US and Canada.')),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.CreateModel(
            name='SupportChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('detail', models.CharField(max_length=200)),
                ('sub', models.CharField(max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Support Channel',
                'verbose_name_plural': 'Support Channels',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='WhyUsFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(help_text='Icon name (e.g. truck, globe, shield)', max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('desc', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Why Us Feature',
                'verbose_name_plural': 'Why Us Features',
                'ordering': ['order'],
            },
        ),
    ]
