# Generated by Django 6.0.5 on 2026-06-16 22:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_abouthighlight_careerperk_commitment_faqitem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalcService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Full Truckload (FTL)', max_length=100)),
                ('key', models.SlugField(help_text='Unique identifier, e.g. ftl', unique=True)),
                ('base_rate', models.DecimalField(decimal_places=2, help_text='Base rate in USD', max_digits=10)),
                ('unit_label', models.CharField(default='per load', help_text='e.g. per load, per pallet', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Calculator Service',
                'verbose_name_plural': 'Calculator Services',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CalcZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. West Coast USA', max_length=100)),
                ('key', models.SlugField(help_text='e.g. west-coast-usa', unique=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Rate Zone',
                'verbose_name_plural': 'Rate Zones',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PortCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cities', to='core.calczone')),
            ],
            options={
                'verbose_name': 'Port / City',
                'verbose_name_plural': 'Port Cities',
                'ordering': ['country', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CalcRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('multiplier', models.DecimalField(decimal_places=3, default=1.0, help_text='Rate multiplier applied to base rate', max_digits=6)),
                ('transit_days', models.CharField(default='3–5', help_text='e.g. 3–5 or Contact us for international', max_length=30)),
                ('dest_zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inbound_routes', to='core.calczone')),
                ('origin_zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outbound_routes', to='core.calczone')),
            ],
            options={
                'verbose_name': 'Route Rate',
                'verbose_name_plural': 'Route Rates',
                'ordering': ['origin_zone__order', 'dest_zone__order'],
                'unique_together': {('origin_zone', 'dest_zone')},
            },
        ),
    ]
