# Generated by Django 6.0.5 on 2026-06-16 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_calcservice_calczone_portcity_calcroute'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='accent_color',
            field=models.CharField(default='#E84231', help_text='Accent/highlight color — e.g. #E84231', max_length=7),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='favicon',
            field=models.ImageField(blank=True, help_text='Favicon (32×32 or 64×64 PNG/ICO)', null=True, upload_to='branding/'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='logo',
            field=models.ImageField(blank=True, help_text='Upload logo (PNG/SVG recommended, white or transparent background)', null=True, upload_to='branding/'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='logo_alt',
            field=models.CharField(blank=True, default='Augustus Corp', help_text='Alt text shown if image fails to load', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='navy_color',
            field=models.CharField(default='#1A3D5C', help_text='Dark navy — e.g. #1A3D5C', max_length=7),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='primary_color',
            field=models.CharField(default='#4A99CC', help_text='Primary blue — e.g. #4A99CC', max_length=7),
        ),
    ]
