# Generated by Django 6.0.5 on 2026-06-17 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_sitesettings_accent_color_sitesettings_favicon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='wordmark_accent',
            field=models.CharField(default='US', help_text='Second part shown in accent color (red)', max_length=50),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='wordmark_main',
            field=models.CharField(default='AUGUST', help_text='First part of the brand name (shown in navy)', max_length=50),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='wordmark_sub',
            field=models.CharField(blank=True, default='CORP', help_text='Small text below the wordmark, e.g. CORP or BROKERAGE', max_length=50),
        ),
    ]
