# Generated by Django 6.0.5 on 2026-06-17 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_sitesettings_wordmark_accent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='logo_dark',
            field=models.ImageField(blank=True, help_text='Dark mode logo (shown on dark backgrounds). Falls back to light logo if not set.', null=True, upload_to='branding/'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='logo',
            field=models.ImageField(blank=True, help_text='Light mode logo (shown on white/light backgrounds)', null=True, upload_to='branding/'),
        ),
    ]
