# Generated by Django 6.0.5 on 2026-06-17 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_sitesettings_logo_dark_alter_sitesettings_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='CargoType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. General Freight', max_length=100)),
                ('key', models.SlugField(unique=True)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('multiplier', models.DecimalField(decimal_places=2, default=1.0, help_text='Cost multiplier (e.g. 1.5 = 50% surcharge)', max_digits=4)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Cargo Type',
                'verbose_name_plural': 'Cargo Types',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TruckType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g. Dry Van 53'", max_length=100)),
                ('key', models.SlugField(unique=True)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('capacity', models.CharField(blank=True, help_text='e.g. 44,000 lbs / 2,700 cu ft', max_length=100)),
                ('rate_per_mile', models.DecimalField(decimal_places=2, help_text='Base rate in USD per mile', max_digits=6)),
                ('min_charge', models.DecimalField(decimal_places=2, help_text='Minimum charge in USD', max_digits=8)),
                ('fuel_surcharge_pct', models.DecimalField(decimal_places=2, default=25.0, help_text='Fuel surcharge percentage (e.g. 25 = 25%)', max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Truck Type',
                'verbose_name_plural': 'Truck Types',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='portcity',
            name='lat',
            field=models.FloatField(blank=True, help_text='Latitude (e.g. 34.052)', null=True),
        ),
        migrations.AddField(
            model_name='portcity',
            name='lng',
            field=models.FloatField(blank=True, help_text='Longitude (e.g. -118.244)', null=True),
        ),
    ]
