# Generated by Django 6.0.5 on 2026-06-17 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_cargotype_trucktype_portcity_lat_portcity_lng'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trucktype',
            options={'ordering': ['order'], 'verbose_name': 'Vehicle Size', 'verbose_name_plural': 'Vehicle Sizes'},
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='google_maps_api_key',
            field=models.CharField(blank=True, default='', help_text='Google Maps API key (enable Distance Matrix API + Maps JavaScript API in Google Cloud Console)', max_length=200),
        ),
    ]
