# Generated by Django 6.0.5 on 2026-06-17 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_trucktype_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trucktype',
            options={'ordering': ['order'], 'verbose_name': 'Vessel Size', 'verbose_name_plural': 'Vessel Sizes'},
        ),
    ]
