# Generated by Django 4.2.30 on 2026-06-17 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_trucktype_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='tagline',
            field=models.CharField(default='Trucking & Brokerage Solutions — Reliable · Scalable · On-Time', max_length=200),
        ),
    ]
