# Generated by Django 4.2.30 on 2026-06-17 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_sitesettings_tagline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='company',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='service',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='avatar_url',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='blog/'),
        ),
        migrations.AddField(
            model_name='company',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='companies/'),
        ),
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='services/'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_image',
            field=models.ImageField(blank=True, help_text='Main photo used in the About section (home & about pages)', null=True, upload_to='site/'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_image_2',
            field=models.ImageField(blank=True, help_text='Small secondary photo in the About section on the home page', null=True, upload_to='site/'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='career_bg',
            field=models.ImageField(blank=True, help_text='Background photo for the Careers page header', null=True, upload_to='site/'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_bg',
            field=models.ImageField(blank=True, help_text='Background photo for the Contact page map banner', null=True, upload_to='site/'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='cta_bg',
            field=models.ImageField(blank=True, help_text='Background photo for the CTA / call-to-action banner', null=True, upload_to='site/'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='gallery_1',
            field=models.ImageField(blank=True, help_text='Gallery image 1 (top-left in Why Us section)', null=True, upload_to='site/gallery/'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='gallery_2',
            field=models.ImageField(blank=True, help_text='Gallery image 2 (bottom-left in Why Us section)', null=True, upload_to='site/gallery/'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='gallery_3',
            field=models.ImageField(blank=True, help_text='Gallery image 3 (top-right in Why Us section)', null=True, upload_to='site/gallery/'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='gallery_4',
            field=models.ImageField(blank=True, help_text='Gallery image 4 (bottom-right in Why Us section)', null=True, upload_to='site/gallery/'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_poster',
            field=models.ImageField(blank=True, help_text='Fallback image shown if the hero video fails to load', null=True, upload_to='site/'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='team/'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='testimonials/'),
        ),
    ]
