# Generated by Django 4.2.30 on 2026-06-17 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_blogpost_image_url_remove_company_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='show_calculator',
            field=models.BooleanField(default=True, help_text='Show the trucking cost calculator for this company on the Companies page'),
        ),
    ]
