# Generated by Django 4.2.30 on 2026-06-18 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_add_company_show_calculator'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, help_text='Company logo shown as the small icon in the card header', null=True, upload_to='companies/logos/'),
        ),
    ]
