# Generated by Django 4.2.30 on 2026-06-18 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_add_company_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='industry',
            name='description',
            field=models.CharField(blank=True, help_text='One-sentence summary shown on the card', max_length=220),
        ),
        migrations.AddField(
            model_name='industry',
            name='icon_name',
            field=models.CharField(blank=True, help_text='SVG icon key: car, chip, cross, gear, bag, plane, bolt, snowflake', max_length=50),
        ),
        migrations.AddField(
            model_name='industry',
            name='logo',
            field=models.ImageField(blank=True, help_text='Custom icon/logo for the card (overrides SVG icon if set)', null=True, upload_to='industries/logos/'),
        ),
        migrations.AddField(
            model_name='industry',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='service',
            name='logo',
            field=models.ImageField(blank=True, help_text='Service icon/logo shown on cards (overrides SVG icon if set)', null=True, upload_to='services/logos/'),
        ),
    ]
