# Generated by Django 4.2.30 on 2026-06-18 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_expand_industry_service_logos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='industry',
            name='description',
            field=models.TextField(blank=True, help_text='Short description shown on the card (2–3 sentences)'),
        ),
    ]
